<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
.linha {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 11px;
	color: #000000;
}
.linhadestaque {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #FF0000;
	font-weight: bold;
	text-transform: uppercase;
	text-decoration: underline blink;
}
.contornolinha {
	border: 1px solid #0000FF;
}
.trocapessoal {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 11px;
	text-decoration: line-through;
	color: #666666;
}
.centraliza {
    background-position: center center;
    text-align: center;
}
.menuformatado {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 10px;
	color: #006699;
	background-color: #00CCFF;
	font-weight: bold;
	border: 1px solid #0099CC;
}
.cabecalhosaldos {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 9px;
	background-color: #99CCFF;
}
.linhasaldos {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 10px;
        color: #000066;
}
.linhasaldosb {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 10px;
        color: #000066;
        height: 10px;
        width: 10px;
        background-color: #99CCCC;
}
.tabelasaldos {
        background-color: #3399FF; 
}
.subtabela {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 11px;
        text-decoration: none;
}
.rodape {
	font-family: "Courier New", Courier, mono;
	font-size: 9px;
	color: #999999;
}
.rodapedestaque {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 10px;
	color: #0066FF;
}
-->
</style>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_showHideLayers() { //v6.0
  var i,p,v,obj,args=MM_showHideLayers.arguments;
  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];
    if (obj.style) { obj=obj.style; v=(v=='show')?'visible':(v=='hide')?'hidden':v; }
    obj.visibility=v; }
}
//-->
</script>
</head>

<body>
